### ISSUE TITLE
Not creating m3u

### ISSUE THREAD

**Issue by Zainpro** [vstavrinov/acestream-service#6]
Upgraded to last version 1.6.1 and I am having this error:  Version 1.4.1 was working good. However following versions do not seem to work for me!:

#EXTM3U
Traceback (most recent call last):
  File "/Users/el/.pyenv/versions/3.9.0/bin/acestream_search", line 8, in <module>
    sys.exit(cli())
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/site-packages/acestream_search/acestream_search.py", line 334, in cli
    for chunk in main(args):
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/site-packages/acestream_search/acestream_search.py", line 321, in main
    for page in pager(args):
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/site-packages/acestream_search/acestream_search.py", line 307, in pager
    for item in page:
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/site-packages/acestream_search/acestream_search.py", line 252, in convert_json
    for channels in get_channels(args):
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/site-packages/acestream_search/acestream_search.py", line 241, in get_channels
    chunk = fetch_page(args, query)['result']['results']
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/site-packages/acestream_search/acestream_search.py", line 168, in fetch_page
    return json.loads(urlopen(url).read().decode('utf8'))
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Users/el/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by vstavrinov** [comment]
It seems You are using acestream_search and not acestream-service, i.e You are trying to run command line utility and don't request to the service. If this is true this is not right place for the issue please close this issue and reopen it in acestream_search repository. If I am wrong explain clearly what You are doing.

**Comment by Zainpro** [comment]
Reopened at acestream_search.
