### ISSUE TITLE
search request failed

### ISSUE THREAD

**Issue by bernardovalente** [vstavrinov/acestream-service#7]
I'm still trying to understand how this works, so when I run:

`$ curl http://192.168.50.233:8008/search.m3u?query=CNN`

I get an a 'search request failed':

```
2023-05-13 23:08:14,776|Thread-498|acestream.webui|unexpected error
Traceback (most recent call last):
  File "ACEStream/WebUI/WebUI.py", line 4514, in handle_media_server_api_request
  File "core/src/search/Manager.pyx", line 254, in 
  File "core/src/search/Manager.pyx", line 228, in 
ACEStream.Core.errors.SearchRequestNetworkError: search request failed
```

also this keeps popping up:

`TrafficStatsSenderThread|acestream.TrafficStatsSender|init: error: <urlopen error failed to connect>`

any idea how to solve this errors? thanks

**Comment by vstavrinov** [comment]
```
docker run --restart always --name=acestream-service --env=SCHEME=http --env=ENTRY=8088 --publish=8088:80 --detach vstavrinov/acestream-service

curl http://localhost:8088/search.m3u?query=CNN
#EXTM3U
#EXTINF:-1,1. CNN Indonesia [ tv; informational ] 2023-05-14 00:49:02 a=1
http://localhost:8088/ace/getstream?infohash=c80c7cffe57ee3cc4171cd65885bbac7a3502ba1
#EXTINF:-1,2. CNN INDONESIA HD [ tv; informational ] 2023-05-14 00:49:02 a=1
http://localhost:8088/ace/getstream?infohash=8262000a94442fe440c835c9abece1e763d862ee
```
